CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    migration_id character varying(150) NOT NULL,
    product_version character varying(32) NOT NULL,
    CONSTRAINT pk___ef_migrations_history PRIMARY KEY (migration_id)
);

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260521165416_InitialCreate') THEN
    CREATE TABLE products (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        name text NOT NULL,
        price_member numeric(10,2) NOT NULL,
        price_guest numeric(10,2) NOT NULL,
        CONSTRAINT pk_products PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260521165416_InitialCreate') THEN
    CREATE TABLE roles (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        name text NOT NULL,
        CONSTRAINT pk_roles PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260521165416_InitialCreate') THEN
    CREATE TABLE users (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        name text NOT NULL,
        surname text,
        saguntino_code text NOT NULL,
        role_id integer NOT NULL,
        CONSTRAINT pk_users PRIMARY KEY (id),
        CONSTRAINT fk_users_roles_role_id FOREIGN KEY (role_id) REFERENCES roles (id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260521165416_InitialCreate') THEN
    CREATE TABLE orders (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        created_at timestamp with time zone NOT NULL,
        total numeric NOT NULL,
        is_paid boolean NOT NULL,
        customer_id integer,
        user_id integer NOT NULL,
        CONSTRAINT pk_orders PRIMARY KEY (id),
        CONSTRAINT fk_orders_users_user_id FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260521165416_InitialCreate') THEN
    CREATE TABLE order_lines (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        quantity integer NOT NULL,
        price_snapshot numeric(10,2) NOT NULL,
        order_id integer NOT NULL,
        product_id integer NOT NULL,
        CONSTRAINT pk_order_lines PRIMARY KEY (id),
        CONSTRAINT fk_order_lines_orders_order_id FOREIGN KEY (order_id) REFERENCES orders (id) ON DELETE CASCADE,
        CONSTRAINT fk_order_lines_products_product_id FOREIGN KEY (product_id) REFERENCES products (id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260521165416_InitialCreate') THEN
    CREATE INDEX ix_order_lines_order_id ON order_lines (order_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260521165416_InitialCreate') THEN
    CREATE INDEX ix_order_lines_product_id ON order_lines (product_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260521165416_InitialCreate') THEN
    CREATE INDEX ix_orders_user_id ON orders (user_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260521165416_InitialCreate') THEN
    CREATE INDEX ix_users_role_id ON users (role_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260521165416_InitialCreate') THEN
    CREATE UNIQUE INDEX ix_users_saguntino_code ON users (saguntino_code);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260521165416_InitialCreate') THEN
    INSERT INTO "__EFMigrationsHistory" (migration_id, product_version)
    VALUES ('20260521165416_InitialCreate', '10.0.7');
    END IF;
END $EF$;
COMMIT;

